# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary

# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

include:
  - project: pstooling/gitlab-templates
    ref: main
    file:
      - templates/pulse-in-pipeline/Scan.gitlab-ci.yml
  - project: security/devops-tools/gitlab-templates
    ref: main
    file:
      - vault.gitlab-ci.yml

workflow:
  rules:
    # Overwrite to unblock other CI jobs
    # ref: https://gitlab-master.nvidia.com/omniverse/farm/devops/ci/gitlab/git/-/blob/main/modules/v2/version/_common.yml
    # run on each merge request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # run on tag creation
    - if: $CI_COMMIT_TAG !~ "/^$/"
    # Prevent branch pipeline, otherwise it would run CI twice, first on the new branch and
    # second on the merge request. We only want to run the CI on the merge request.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never

variables:
  TEST_REPORT_FILE: report.xml
  NSPECT_ID: NSPECT-K76E-VNQ5
  VAULT_ADDR: https://prod.vault.nvidia.com
  VAULT_NAMESPACE: backstage
  VAULT_ROLE: sw-cloud-role
  VAULT_MOUNT_PATH: auth/jwt/nvidia/gitlab-master
  VAULT_SECRETS_DEST: ./secrets/secrets
  SONAR_HOST_URL: https://sonar-sw.nvidia.com/

default:
  tags:
    - generic

# Only for CI Build, not for production run time usage
image: golang:1.23.0

stages:
  - test
  - integration-test
  - build
  - scan
  - deploy

.rules:
  # Do not run on schedule events
  do_not_run_on_schedule:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
  # Do not run on tags
  do_not_run_on_tags:
    - if: $CI_COMMIT_TAG !~ "/^$/"
      when: never
  # Run on specific branches
  run_on_specific_branches:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release\/.*$/

.vault-secrets:
  id_tokens:
    VAULT_ID_TOKEN:
      aud: $VAULT_ADDR
  extends:
    - .nv-vault
  before_script:
    - !reference [.nv-vault, before_script]
    - vault agent -config ./vault-agent/config-local.hcl once
    - source "${VAULT_SECRETS_DEST}"

golangci-lint:
  stage: test
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0
    - golangci-lint run

.test-base:
  before_script:
    - go install gotest.tools/gotestsum@latest
  artifacts:
    when: always
    reports:
      junit: $TEST_REPORT_FILE

unit-test:
  stage: test
  extends:
    - .test-base
  script:
    - make NGC_API_KEY=$NGC_API_KEY TEST_REPORT_FILE=$TEST_REPORT_FILE test
  artifacts:
    paths:
     - coverage_ut.out
     - report_ut.xml

# XXX: We pass the NGC_API_KEY with gitlab CI variable in here,
#   since the golang build image is distroless, which cannot install unzip for nvvault installation.
# And we don't want to maintain another build image in here.
integration-test:
  stage: integration-test
  extends:
    - .test-base
  script:
    - make NGC_API_KEY=$NGC_API_KEY TEST_REPORT_FILE=$TEST_REPORT_FILE testacc
  artifacts:
    paths:
     - coverage_acc.out
     - report_acc.xml
build:
  stage: build
  rules:
    # Don't run when triggered with tag, since the publish step will include build process.
    - if: $CI_COMMIT_TAG !~ "/^$/"
      when: never
    - when: always
  script:
    - go install github.com/goreleaser/goreleaser/v2@v2.2.0
    - goreleaser release --clean --snapshot --skip=publish,announce,sign
  artifacts:
    paths:
     - dist/*.zip

sonarqube-check:
  stage: scan
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop
  needs:
  - job: unit-test
    artifacts: true
  - job: integration-test
    artifacts: true

sonarqube-vulnerability-report:
  stage: scan
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=nvb_tools_terraform-provider-ngc_4fe819bd-82c6-4414-9d03-a5b71497c2f4&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check

# XXX: image is overwrote by gitlab job template.
security:scan:
  stage: scan
  rules:
    - !reference [.rules, do_not_run_on_schedule]
    - !reference [.rules, do_not_run_on_tags]
    - !reference [.rules, run_on_specific_branches]
  extends:
    - .vault-secrets
    - .scan-with-report-no-fail
  variables:
    PULSE_NSPECT_ID: $NSPECT_ID
    PULSE_REPO_URL: "${CI_PROJECT_URL}.git"
    PULSE_SCAN_PROJECT: "terraform-provider-ngc"
    PULSE_SCAN_PROJECT_VERSION: "${CI_COMMIT_BRANCH}"
    PULSE_SCAN_VULNERABILITY_REPORT: "nspect_scan_report.json"
    PULSE_SCAN_BINARY_FILE_NAME_PATTERNS: "*.zip"
    PULSE_SCAN_RETRIES: 15
    RELATIVE_PATH_TO_SCAN: "./dist"
  dependencies:
    - build

# XXX: We pass the deploy key (ARTIFACTORY_URM_SECRET, ARTIFACTORY_URM_USERNAME) with gitlab CI variable in here,
#   since the golang build image is distroless, which cannot install unzip for nvvault installation.
# And we don't want to maintain another build image in here.
release:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG !~ "/^$/"
  extends:
    - .vault-secrets
  variables:
    VAULT_ROLE: gitlab-ci-reader-for-tag # Since the phase will be only executed when tag build.
  script:
    - apt update
    - apt install -y python3 python3-pip
    - python3 -m pip install nvsec -i https://urm.nvidia.com/artifactory/api/pypi/sw-cloudsec-pypi/simple --extra-index-url https://urm.nvidia.com/artifactory/api/pypi/sw-cftt-pypi-local/simple --break-system-packages
    - go install github.com/goreleaser/goreleaser/v2@v2.2.0
    - git clean -f -d # Clean up secret files since we already push them into environment variables, and dirty state repository cannot be built by goreleaser.
    - goreleaser release --clean
